### ISSUE TITLE
Collection order in _config.yml is not working properly

### ISSUE THREAD

**Issue by benjbach** [visualinteractivedata/visualinteractivedata.github.io#11]
The project order specified in _config.yml is not the one displayed on index.html.

**Comment by jamesscottbrown** [comment]
The problem is that the `order` only takes effect for Jekyll version >= 4.0, but currently [GitHub Pages uses 3.9.0](https://pages.github.com/versions/).

Until they upgrade, I think the only work-around is to rename the project files to include the intended position (`01_education.md`, `02_clinical_guidelines.md`, ...), so that the lexicographic order matches the intended order.

**Comment by jamesscottbrown** [comment]
See: https://github.com/github/pages-gem/issues/651

It looks like the upgrade to Jekyll 4 won't happen for a while, so we should probably think about using GitHub Actions to build the site. I can set this up once the current round of paper submissions is done.

**Comment by sarah37** [comment]
I just switched the build workflow to GitHub Actions in [b00fd19](https://github.com/visualinteractivedata/visualinteractivedata.github.io/commit/b00fd19771aac4f51625822dd3aad1081a37b7a7). So now we're ready to start looking into upgrading our jekyll installation and plugins, but this will probably require some testing to make sure everything still works.

**Comment by sarah37** [comment]
Done! We're now using jekyll directly, not through the github-pages package. I've upgraded it to the latest version, should be easy to update in the future. See commit fff5ef7
Ordering works as well now so I'm closing this issue.
